module.exports = {
  '.php': 'ace/mode/php',
  '.js': 'ace/mode/javascript',
  '.json': 'ace/mode/javascript',
  '.c': 'ace/mode/c_cpp',
  '.cpp': 'ace/mode/c_cpp',
  '.cpp': 'ace/mode/c_cpp',
  '.css': 'ace/mode/css',
  '.scss': 'ace/mode/sass',
  '.sass': 'ace/mode/sass',
  '.coffee': 'ace/mode/coffee',
  '.cs': 'ace/mode/csharp',
  '.html': 'ace/mode/html',
  '.htm': 'ace/mode/html',
  '.java': 'ace/mode/java',
  '.less': 'ace/mode/less',
  '.md': 'ace/mode/markdown',
  '.py': 'ace/mode/python',
  '.rb': 'ace/mode/ruby',
  '.twig': 'ace/mode/twig',
  '.xml': 'ace/mode/xml',
  '.svg': 'ace/mode/xml',
  '.yaml': 'ace/mode/yaml',
  '.yml': 'ace/mode/yaml'
};