module.exports = {
    '.txt': 'text',
    '.php': 'php',
    '.js': 'javascript',
    '.json': 'javascript',
    '.c': 'c_cpp',
    '.cpp': 'c_cpp',
    '.cpp': 'c_cpp',
    '.css': 'css',
    '.scss': 'scss',
    '.sass': 'sass',
    '.cs': 'csharp',
    '.html': 'html',
    '.htm': 'html',
    '.java': 'java',
    '.less': 'less',
    '.md': 'markdown',
    '.py': 'python',
    '.rb': 'ruby',
    '.twig': 'twig',
    '.xml': 'xml',
    '.svg': 'xml',
    '.yaml': 'yaml',
    '.yml': 'yaml',
    '.sh': 'sh'
};