#!/usr/bin/env node

var express = require('express');
var app = express();
var swig = require('swig');
app.engine('html', swig.renderFile);
app.set('view engine', 'html');

// todo: change cache settings later
app.set('view cache', false);
swig.setDefaults({
  cache: false
});

app.use('/', express.static(__dirname + '/public'));

var tmp = [{
  title: 'zenturio-solutions',
  type: 'dir',
  items: [{
    title: 'cache',
    type: 'dir',
    items: [{
      title: 'test.js',
      type: 'file',
    }, {
      title: 'some-data.html',
      type: 'file',
    }, {
      title: 'ookay.dat',
      type: 'file',
    }, ]
  }, {
    title: 'index.js',
    type: 'file',
  }, ]
}];

app.get('/', function(req, res) {
  res.render('tree', {
    items: tmp
  });
});

app.get('/editor', function(req, res) {
  res.render('editor');
});

var port = 3000;
app.listen(port, function(err) {
  if (!err) {
    console.log('Zenturio Editor started at port ', port);
  }
});